# Auto-generated by tools/s2h/gen_s2h_configs.py -- DO NOT EDIT MANUALLY.
# Dataset settings below are copied verbatim from Domain-RAG's reproduction config,
# so that the comparison is apples-to-apples.
_base_ = [
    '../grounding_dino/grounding_dino_swin-b_finetune_16xb2_1x_coco.py',
]

# Auto-generated config for ArTaxOr 1-shot

# dataset settings
dataset_type = 'CocoDataset'
data_root = 'data/ArTaxOr/'

metainfo = dict(
    classes = ('Araneae', 'Coleoptera', 'Diptera', 'Hemiptera', 'Hymenoptera', 'Lepidoptera', 'Odonata')
)

train_ann_file = 'annotations/1_shot.json'

backend_args = None

train_pipeline = [
    dict(type='LoadImageFromFile', backend_args=backend_args),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='CachedMosaic', img_scale=(640, 640), pad_val=114.0, prob=0.6),
    dict(type='YOLOXHSVRandomAug'),
    dict(type='RandomFlip', prob=0.5),
    dict(
        type='CachedMixUp',
        img_scale=(640, 640),
        ratio_range=(1.0, 1.0),
        max_cached_images=10,
        pad_val=(114, 114, 114),
        prob = 0.3),
    dict(
        type='RandomChoice',
        transforms=[
            [
                dict(
                    type='RandomChoiceResize',
                    scales=[(480, 1333), (512, 1333), (544, 1333), (576, 1333),
                            (608, 1333), (640, 1333), (672, 1333), (704, 1333),
                            (736, 1333), (768, 1333), (800, 1333)],
                    keep_ratio=True)
            ],
            [
                dict(
                    type='RandomChoiceResize',
                    scales=[(400, 4200), (500, 4200), (600, 4200)],
                    keep_ratio=True),
                dict(
                    type='RandomCrop',
                    crop_type='absolute_range',
                    crop_size=(384, 600),
                    allow_negative_crop=True),
                dict(
                    type='RandomChoiceResize',
                    scales=[(480, 1333), (512, 1333), (544, 1333), (576, 1333),
                            (608, 1333), (640, 1333), (672, 1333), (704, 1333),
                            (736, 1333), (768, 1333), (800, 1333)],
                    keep_ratio=True)
            ]
        ]),
    dict(
        type='PackDetInputs',
        meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                   'scale_factor', 'flip', 'flip_direction', 'text',
                   'custom_entities'))
]

test_pipeline = [
    dict(type='LoadImageFromFile', backend_args=backend_args),
    dict(type='FixScaleResize', scale=(800, 1333), keep_ratio=True),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='PackDetInputs',
        meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                   'scale_factor', 'text', 'custom_entities'))
]

train_dataloader = dict(
    batch_size=4,
    num_workers=8,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    batch_sampler=dict(type='AspectRatioBatchSampler'),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file=train_ann_file,
        metainfo=metainfo,
        data_prefix=dict(img='train/'),
        pipeline=train_pipeline,
        filter_cfg=dict(filter_empty_gt=False),
        return_classes=True))

val_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file='annotations/test.json',
        data_prefix=dict(img='test/'),
        test_mode=True,
        metainfo=metainfo,
        pipeline=test_pipeline,
        return_classes=True))

test_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file='annotations/test.json',
        data_prefix=dict(img='test/'),
        test_mode=True,
        metainfo=metainfo,
        pipeline=test_pipeline,
        return_classes=True))

val_evaluator = dict(
    type='CocoMetric',
    ann_file=data_root + 'annotations/test.json',
    metric='bbox',
    classwise=True,
    format_only=False,
    backend_args=backend_args)

test_evaluator = dict(
    type='CocoMetric',
    ann_file=data_root + 'annotations/test.json',
    metric='bbox',
    classwise=True,
    format_only=False,
    backend_args=backend_args)


# ---------------------------------------------------------------------------
# S2H-CD-FSOD: knowledge-enhanced Hard-Soft routing on top of the exact
# Grounding DINO Swin-B recipe reproduced by Domain-RAG.
# ---------------------------------------------------------------------------
model = dict(
    type='S2HGroundingDINO',
    bbox_head=dict(
        type='S2HGroundingDINOHead',
        s2h_cfg=dict(
            enabled=True,
            stage='full',
            classes=metainfo['classes'],
            knowledge_path='work_dirs/s2h_knowledge/ArTaxOr_1shot.pth',
            gamma=1.0,
            alpha_max=0.5,
            g_max=0.5,
            theta=0.5,
            T_u=0.1,
            init_alpha_bias=-2.5,
            init_alpha_from_reliability=True,
            positive_only=True,
            center_delta=True,
            soft_mix=0.35,
            reliability_power=0.5,
            alpha_rel_floor=0.1,
            alpha_rel_scale=0.8,
            train_injection=False,
            res_weight=0.0,
            con_weight=0.0)))

# training loop / schedule (mirrors the Domain-RAG launch script)
max_epochs = 30
train_cfg = dict(type='EpochBasedTrainLoop', max_epochs=max_epochs,
                 val_interval=1)
param_scheduler = [
    dict(
        type='MultiStepLR',
        begin=0,
        end=max_epochs,
        by_epoch=True,
        milestones=[11],
        gamma=0.1)
]

# Save checkpoints during training, but do not select on the query set.  The
# launcher evaluates the fixed final epoch because this protocol has no
# independent validation split.
default_hooks = dict(
    checkpoint=dict(type='CheckpointHook', interval=1,
                    save_best=None,
                    max_keep_ckpts=3))
